# Generated by Django 6.0.1 on 2026-01-27 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='項目名稱')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金額')),
                ('category', models.CharField(choices=[('SALARY', '薪資支出'), ('EQUIPMENT', '設備採購'), ('REVENUE', '專案收入'), ('OFFICE', '行政雜支')], max_length=20, verbose_name='分類')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
