# Generated by Django 6.0.1 on 2026-01-27 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '財務單據', 'verbose_name_plural': '財務流水帳'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='系統建立時間'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='正數為收入，負數為支出', max_digits=12, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALARY', '薪資支出'), ('EQUIPMENT', '設備採購'), ('REVENUE', '專案收入'), ('OFFICE', '行政雜支')], db_index=True, max_length=20, verbose_name='費用分類'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='經手人'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(help_text='請輸入簡短的交易摘要（如：12月份房租）', max_length=200, verbose_name='項目名稱'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'category'], name='finance_tra_date_765fff_idx'),
        ),
    ]
