# Generated by Django 6.0.1 on 2026-01-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '使用者', 'verbose_name_plural': '使用者列表'},
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '系統管理員'), ('HR', '人事專員'), ('FINANCE', '財務會計'), ('CRM', '業務代表')], default='ADMIN', max_length=20, verbose_name='職位角色'),
        ),
    ]
