# Generated by Django 6.0.1 on 2026-01-27 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('company', models.CharField(max_length=100, verbose_name='所屬公司')),
                ('email', models.EmailField(max_length=254, verbose_name='聯繫郵箱')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('stage', models.CharField(choices=[('LEAD', '潛在客戶'), ('DISCOVERY', '需求確認'), ('PROPOSAL', '方案報價'), ('NEGOTIATION', '商議談判'), ('WON', '成功結案'), ('LOST', '開發失敗')], default='LEAD', max_length=20, verbose_name='開發階段')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='預估成交金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'CRM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='負責業務')),
            ],
        ),
    ]
