# Generated by Django 6.0.1 on 2026-01-27 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at', '-estimated_value'], 'verbose_name': '客戶', 'verbose_name_plural': '客戶資料庫'},
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CRM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='負責業務專員'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(db_index=True, max_length=100, verbose_name='所屬企業'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='系統建立時間'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='聯繫郵箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='預計成交的合同金額', max_digits=12, verbose_name='預估價值'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='客戶姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stage',
            field=models.CharField(choices=[('LEAD', '潛在客戶'), ('DISCOVERY', '需求確認'), ('PROPOSAL', '方案報價'), ('NEGOTIATION', '商議談判'), ('WON', '成功結案'), ('LOST', '開發失敗')], db_index=True, default='LEAD', max_length=20, verbose_name='開發階段'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['stage', 'company'], name='crm_custome_stage_89c754_idx'),
        ),
    ]
